/** Public domain classical artwork — verified depictions only */
export const personImages: Record<string, {
  url: string;
  title: string;
  artist: string;
  /** CSS object-position value — keeps the subject's face as the focal point */
  focus?: string;
}> = {
  adam:       { url: "/art/adam.jpg",       title: "The Creation of Adam",                    artist: "Michelangelo",                          focus: "center 42%" },
  abel:       { url: "/art/abel.jpg",       title: "Cain Slaying Abel",                      artist: "Pier Francesco Mola" },
  cain:       { url: "/art/cain.jpg",       title: "Cain and Abel",                          artist: "Odilon Redon" },
  seth:       { url: "/art/seth.jpg",       title: "The Rebuke of Adam and Eve",             artist: "Charles Joseph Natoire" },
  "enoch-s":  { url: "/art/enoch-s.jpg",    title: "God Took Enoch",                         artist: "Bible illustration, 19th c.",           focus: "center 3%" },
  enosh:      { url: "/art/enosh.jpg",      title: "The First Sermon in the Tribe of Seth",  artist: "Johann Wilhelm Schirmer" },
  methuselah: { url: "/art/methuselah.jpg", title: "Methuselah",                             artist: "Bartolom\u00E9 Bermejo" },
  "lamech-s": { url: "/art/lamech-s.jpg",   title: "Noah Leading Animals into the Ark",      artist: "Giovanni Benedetto Castiglione" },
  "lamech-c": { url: "/art/lamech-c.jpg",   title: "Lamech and Cain",                        artist: "Lucas van Leyden" },
  jabal:      { url: "/art/jabal.jpg",      title: "Bedouin Tent",                           artist: "John Singer Sargent" },
  tubalcain:  { url: "/art/tubalcain.jpg",  title: "The Blacksmith\u2019s Forge",            artist: "Johann Hamza" },
  noah:       { url: "/art/noah.jpg",       title: "Noah and the Animals Entering the Ark",  artist: "Giovanni Benedetto Castiglione",        focus: "center 60%" },
  ham:        { url: "/art/ham.jpg",        title: "The Drunkenness of Noah",                artist: "Gustave Dor\u00E9" },
  shem:       { url: "/art/shem.jpg",       title: "Shem and Japheth Cover Noah",            artist: "Met Museum",                            focus: "center 32%" },
  japheth:    { url: "/art/japheth.jpg",    title: "Noah",                                   artist: "Lorenzo Monaco" },
  gomer:      { url: "/art/gomer.jpg",      title: "Scythians and Habitants of Asia Minor",  artist: "Adolf Rosenberg" },
  ashkenaz:   { url: "/art/ashkenaz.jpg",   title: "Scythian and Parthian Warriors",         artist: "Friedrich Hottenroth" },
  magog:      { url: "/art/magog.jpg",      title: "Gog and Magog",                          artist: "Jacob George Strutt" },
  madai:      { url: "/art/elam.jpg",       title: "Lions Frieze from the Palace at Susa",   artist: "James Ward" },
  tarshish:   { url: "/art/tarshish.jpg",   title: "Phoenician Ships",                       artist: "H. G. Swanwick" },
  kittim:     { url: "/art/kittim.jpg",     title: "A Phoenician Colony",                    artist: "Hendrik Willem Van Loon" },
  dodanim:    { url: "/art/dodanim.jpg",    title: "A Phoenician Trader",                    artist: "Hendrik Willem Van Loon" },
  mizraim:    { url: "/art/mizraim.jpg",    title: "Ancient Egypt",                          artist: "Adolf Rosenberg" },
  nimrod:     { url: "/art/nimrod.jpg",     title: "The Tower of Babel",                     artist: "Met Museum" },
  cush:       { url: "/art/cush.jpg",       title: "The Queen of Sheba before Solomon",      artist: "Anonymous" },
  sidon:      { url: "/art/sidon.jpg",      title: "A Phoenician Trader",                    artist: "Hendrik Willem Van Loon" },
  lot:        { url: "/art/lot.jpg",        title: "Lot and His Family Fleeing Sodom",       artist: "Met Museum" },
  moab:       { url: "/art/moab.jpg",       title: "The Burning of Sodom",                   artist: "Camille Corot" },
  milcah:     { url: "/art/milcah.jpg",     title: "Rebecca and Eliezer at the Well",        artist: "Johann K\u00F6nig" },
  arphaxad:   { url: "/art/arphaxad.jpg",   title: "The Tower of Babel",                     artist: "Pieter Bruegel the Elder" },
  aram:       { url: "/art/aram.jpg",       title: "Esron and Aram, Ancestors of Christ",    artist: "Adamo Scultori" },
  elam:       { url: "/art/elam.jpg",       title: "Lions Frieze from the Palace at Susa",   artist: "James Ward" },
  peleg:      { url: "/art/peleg.jpg",      title: "The Tower of Babel",                     artist: "Jan Brueghel the Elder" },
  nahor1:     { url: "/art/nahor1.jpg",     title: "Eliezer and Rebecca at the City of Nahor", artist: "Domenico Piola" },
  nahor2:     { url: "/art/nahor2.jpg",     title: "Eliezer and Rebecca at the City of Nahor", artist: "Domenico Piola" },
  terah:      { url: "/art/terah.jpg",      title: "Abraham\u2019s Parting from Lot",        artist: "Jan Victors" },
  haran:      { url: "/art/haran.jpg",      title: "Abraham Leaves Haran",                   artist: "Francesco Bassano the Younger" },
  bethuel:    { url: "/art/bethuel.jpg",     title: "Laban and Rebecca Receiving Eliezer",    artist: "Maerten De Vos" },
  abraham:    { url: "/art/abraham.jpg",    title: "The Sacrifice of Isaac",                 artist: "Giovanni Domenico Tiepolo",             focus: "55% 7%" },
  ishmael:    { url: "/art/ishmael.jpg",    title: "Hagar and Ishmael",                      artist: "Benjamin West" },
  nebajoth:   { url: "/art/nebajoth.jpg",   title: "An Arabian in the Desert",               artist: "Charles Tschaggeny" },
  kedar:      { url: "/art/kedar.jpg",      title: "An Arab Caravan",                        artist: "Alberto Pasini" },
  midian:     { url: "/art/midian.jpg",     title: "Moses and the Burning Bush",             artist: "Gerard Hoet" },
  isaac:      { url: "/art/isaac.jpg",      title: "Isaac Blessing Jacob",                   artist: "Gerbrand van den Eeckhout",             focus: "55% 30%" },
  rebekah:    { url: "/art/rebekah.jpg",    title: "The Abduction of Rebecca",               artist: "Eug\u00E8ne Delacroix" },
  esau:       { url: "/art/esau.jpg",       title: "Esau Selling His Birthright",            artist: "Met Museum" },
  jacob:      { url: "/art/jacob.jpg",      title: "Jacob Wrestling with the Angel",         artist: "Met Museum",                            focus: "center 22%" },
  laban:      { url: "/art/laban.jpg",      title: "Laban Searching for his Idols",          artist: "Jan de Bray" },
  rachel:     { url: "/art/rachel.jpg",     title: "Jacob Draws Water for Rachel",           artist: "Claude Mellan" },
  leah:       { url: "/art/leah.jpg",       title: "Journey of Jacob and Rachel to Canaan",  artist: "Stefano della Bella" },
  dinah:      { url: "/art/dinah.jpg",      title: "Study for the Rape of Dinah",            artist: "Fra Bartolomeo" },
  simeon:     { url: "/art/simeon.jpg",     title: "The Rape of Dinah",                      artist: "James Tissot" },
  levi:       { url: "/art/levi.jpg",       title: "Moses with Aaron and Hur",               artist: "Joseph von F\u00FChrich" },
  judah:      { url: "/art/judah.jpg",      title: "Judah and Tamar",                        artist: "Met Museum",                            focus: "center 30%" },
  gad:        { url: "/art/gad.jpg",        title: "Jacob Blessing his Sons",                artist: "Adam van Noort" },
  asher:      { url: "/art/asher.jpg",      title: "Jacob with Leah and Rachel",             artist: "Jan Ladislaw Sykora" },
  issachar:   { url: "/art/issachar.jpg",   title: "Jacob Blesses Joseph\u2019s Sons",       artist: "Robert Payton Reid" },
  zebulun:    { url: "/art/zebulun.jpg",    title: "Jacob, Judah and Leah, Ancestors of Christ", artist: "Adamo Scultori" },
  dan:        { url: "/art/dan.jpg",        title: "Samson",                                 artist: "Solomon Joseph Solomon" },
  naphtali:   { url: "/art/naphtali.jpg",   title: "Jael and Sisera",                        artist: "Artemisia Gentileschi" },
  reuben:     { url: "/art/reuben.jpg",     title: "Joseph Receives his Brothers in Egypt",  artist: "Bacchiacca" },
  joseph:     { url: "/art/joseph.jpg",     title: "Joseph Interpreting Dreams",              artist: "Met Museum" },
  benjamin:   { url: "/art/benjamin.jpg",   title: "The Story of Joseph",                    artist: "Biagio d\u2019Antonio" },
  manasseh:   { url: "/art/manasseh.jpg",   title: "Jacob Blessing the Sons of Joseph",      artist: "Guercino" },
  ephraim:    { url: "/art/ephraim.jpg",    title: "Jacob Blessing Ephraim and Manasseh",    artist: "Frederick Pickersgill" },
  perez:      { url: "/art/perez.jpg",      title: "Judah and Tamar",                        artist: "Wenceslaus Hollar" },
  hezron:     { url: "/art/hezron.jpg",     title: "Esron and Aram, Ancestors of Christ",    artist: "Adamo Scultori" },
  nahshon:    { url: "/art/nahshon.jpg",    title: "The Crossing of the Red Sea",            artist: "Frans Francken the Younger" },
  salmon:     { url: "/art/salmon.jpg",     title: "The Walls of Jericho Falling",           artist: "Gustave Dor\u00E9" },
  ram:        { url: "/art/ram.jpg",        title: "Tree of Jesse",                          artist: "Hans Holbein the Elder" },
  boaz:       { url: "/art/boaz.jpg",       title: "Ruth and Boaz",                          artist: "Artvee Collection",                     focus: "center 18%" },
  obed:       { url: "/art/obed.jpg",       title: "Ruth and Boaz",                          artist: "Met Museum" },
  jesse:      { url: "/art/jesse.jpg",      title: "Tree of Jesse",                          artist: "Italian, 17th century" },
  david:      { url: "/art/david.jpg",      title: "David",                                  artist: "Lorenzo Monaco",                        focus: "center 12%" },
  /* ── Downloaded from Wikimedia / archives ── */
  canaan:     { url: "/art/canaan.jpg",    title: "Noah Curses Ham and Canaan",             artist: "Bible illustration, 19th c." },
  heth:       { url: "/art/heth.jpg",      title: "Lion Gate, Hattusa",                     artist: "Hittite, c. 1300 BC" },
  phut:       { url: "/art/phut.jpg",      title: "Libyans, from Medinet Habu",             artist: "Ancient Egyptian relief" },
  ludim:      { url: "/art/ludim.jpg",     title: "Ramses II at Kadesh",                    artist: "Nordisk familjebok" },
  anamim:     { url: "/art/anamim.jpg",    title: "Great Temple at Abu Simbel",             artist: "David Roberts" },
  lehabim:    { url: "/art/lehabim.jpg",   title: "Libyan Chief",                           artist: "Ramesses III faience tile" },
  tubal:      { url: "/art/tubal.jpg",     title: "Descendants of Noah",                    artist: "Nuremberg Chronicle, 1493" },
  meshech:    { url: "/art/meshech.jpg",   title: "Warrior God, King\u2019s Gate, Hattusa", artist: "Hittite, 14th\u201313th c. BC" },
  tiras:      { url: "/art/tiras.jpg",     title: "Thracian Tomb of Kazanlak Fresco",       artist: "Thracian, 4th c. BC" },
  riphath:    { url: "/art/riphath.jpg",   title: "Caucasus Mountains from the Sea",        artist: "Ivan Aivazovsky, 1899" },
  togarmah:   { url: "/art/togarmah.jpg",  title: "Statuette of God Teisheba",              artist: "Urartian bronze, 8th c. BC" },
  javan:      { url: "/art/javan.jpg",     title: "Greek Soldiers",                         artist: "Greco-Persian Wars illustration" },
  mahalalel:  { url: "/art/mahalalel.jpg", title: "Mahalalel, Liber Chronicarum",           artist: "Wolgemut & Pleydenwurff, 1493" },
  "enoch-c":  { url: "/art/enoch-c.jpg",  title: "Cain Builds the City of Enoch",          artist: "Julius Schnorr von Carolsfeld, 1860" },
  jared:      { url: "/art/jared.jpg",     title: "Jared, Patriarch",                       artist: "Nuremberg Chronicle, 1493" },
  irad:       { url: "/art/irad.jpg",     title: "Irad, Son of Enoch",                     artist: "Nuremberg Chronicle, 1493" },
};
